using System.Text.RegularExpressions;
using PiPlay.Models;

namespace PiPlay.Services;

/// <summary>
/// Parses supported YouTube URLs and builds watch/embed target URLs (spec 12.4).
/// Pure and side-effect free so it is easy to unit-test. Owns nothing about the UI or
/// WebView - it only understands URL shapes and timestamps.
/// </summary>
public static class YouTubeUrlHelper
{
    private static readonly Regex VideoIdRegex = new(@"^[A-Za-z0-9_-]{11}$", RegexOptions.Compiled);
    private static readonly Regex PlaylistIdRegex = new(@"^[A-Za-z0-9_-]{2,128}$", RegexOptions.Compiled);
    private static readonly Regex HmsRegex = new(@"^(?:(\d+)h)?(?:(\d+)m)?(?:(\d+)s)?$", RegexOptions.Compiled | RegexOptions.IgnoreCase);

    /// <summary>Try to parse any supported YouTube URL (or a bare 11-char video id).</summary>
    public static bool TryParse(string? input, out YouTubeTarget target)
    {
        target = new YouTubeTarget();
        if (string.IsNullOrWhiteSpace(input)) return false;

        var text = input.Trim();
        if (VideoIdRegex.IsMatch(text)) { target.VideoId = text; return true; }

        if (!text.Contains("://")) text = "https://" + text;
        if (!Uri.TryCreate(text, UriKind.Absolute, out var uri)) return false;
        if (uri.Scheme != Uri.UriSchemeHttp && uri.Scheme != Uri.UriSchemeHttps) return false;

        var host = uri.Host.ToLowerInvariant();
        var query = ParseQuery(uri.Query);
        var segments = uri.AbsolutePath.Trim('/').Split('/', StringSplitOptions.RemoveEmptyEntries);

        if (host == "youtu.be")
        {
            if (segments.Length >= 1 && IsVideoId(segments[0])) target.VideoId = segments[0];
            if (query.TryGetValue("list", out var l)) ApplyList(target, l);
            if (query.TryGetValue("t", out var t)) target.StartSeconds = ParseTime(t);
            return target.IsValid;
        }

        if (!NavigationPolicy.IsYouTubeHost(host)) return false;

        // Path-based ids: /embed/ID, /shorts/ID, /v/ID, /live/ID
        if (segments.Length >= 2 &&
            (segments[0] is "embed" or "shorts" or "v" or "live") && IsVideoId(segments[1]))
        {
            target.VideoId = segments[1];
        }

        // watch?v=ID (or any page carrying ?v=)
        if (query.TryGetValue("v", out var v) && IsVideoId(v)) target.VideoId = v;

        if (segments.Length >= 1 && segments[0] == "playlist" && target.VideoId is null)
            target.IsPlaylistOnly = true;

        if (query.TryGetValue("list", out var list)) ApplyList(target, list);

        if (query.TryGetValue("t", out var ts)) target.StartSeconds = ParseTime(ts);
        else if (query.TryGetValue("start", out var st)) target.StartSeconds = ParseTime(st);

        return target.IsValid;
    }

    /// <summary>Build a normal-mode watch URL (default playback path, spec 10.1).</summary>
    public static string BuildWatchUrl(YouTubeTarget target, int? seconds = null)
    {
        var s = seconds ?? target.StartSeconds;
        if (!string.IsNullOrEmpty(target.VideoId))
        {
            var url = $"https://www.youtube.com/watch?v={target.VideoId}";
            if (!string.IsNullOrEmpty(target.PlaylistId)) url += $"&list={target.PlaylistId}";
            if (s is > 0) url += $"&t={s}s";
            return url;
        }
        if (!string.IsNullOrEmpty(target.PlaylistId))
            return $"https://www.youtube.com/playlist?list={target.PlaylistId}";
        return "https://www.youtube.com/";
    }

    /// <summary>
    /// Build the local compact-shell URL (spec 10.3): the shell base (a WebView2 virtual host such
    /// as <c>https://piplay.local/player.html</c>) plus only the non-sensitive playback target —
    /// video id, playlist id, and start seconds. No credentials, cookies, or tokens. The shell
    /// reads these query params and drives the YouTube IFrame API player. The base is injected so
    /// this helper stays WebView-agnostic (the host owns the virtual-host name).
    /// </summary>
    public static string BuildShellUrl(YouTubeTarget target, int? seconds, string shellPlayerBaseUrl)
    {
        var s = seconds ?? target.StartSeconds ?? 0;
        var query = new List<string>();
        if (!string.IsNullOrEmpty(target.VideoId)) query.Add("v=" + Uri.EscapeDataString(target.VideoId));
        if (!string.IsNullOrEmpty(target.PlaylistId) && !IsAutoGeneratedList(target.PlaylistId))
            query.Add("list=" + Uri.EscapeDataString(target.PlaylistId));
        if (s > 0) query.Add("start=" + s);
        return query.Count == 0 ? shellPlayerBaseUrl : shellPlayerBaseUrl + "?" + string.Join("&", query);
    }

    /// <summary>
    /// Build a direct compact embed URL (spec 10.2). Reserved for a future direct-embed fallback
    /// tier; the active compact path uses the local shell (<see cref="BuildShellUrl"/>) + IFrame API.
    /// </summary>
    public static string BuildEmbedUrl(YouTubeTarget target, int? seconds = null)
    {
        var s = seconds ?? target.StartSeconds ?? 0;
        var embeddableList = IsAutoGeneratedList(target.PlaylistId) ? null : target.PlaylistId;
        if (!string.IsNullOrEmpty(target.VideoId))
        {
            var url = $"https://www.youtube.com/embed/{target.VideoId}?autoplay=1";
            if (!string.IsNullOrEmpty(embeddableList)) url += $"&list={embeddableList}";
            if (s > 0) url += $"&start={s}";
            return url;
        }
        if (!string.IsNullOrEmpty(embeddableList))
            return $"https://www.youtube.com/embed/videoseries?list={embeddableList}&autoplay=1";
        return "https://www.youtube.com/";
    }

    /// <summary>Parse a YouTube time value: plain seconds ("90"), "90s", or "1h2m3s".</summary>
    public static int? ParseTime(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return null;
        value = value.Trim();

        if (int.TryParse(value, out var plain)) return plain >= 0 ? plain : null;

        var m = HmsRegex.Match(value);
        if (!m.Success || (!m.Groups[1].Success && !m.Groups[2].Success && !m.Groups[3].Success))
            return null;

        // Out-of-range components (e.g. a pasted URL carrying t=99999999999h) must degrade to
        // "no offset" - never throw or silently overflow into a wrong timestamp. Plain int.Parse +
        // unchecked arithmetic did both, surfacing the generic crash dialog instead of failing
        // gracefully (spec 17: broken URLs fail gracefully).
        if (!TryParseComponent(m.Groups[1], out var h) ||
            !TryParseComponent(m.Groups[2], out var min) ||
            !TryParseComponent(m.Groups[3], out var sec))
            return null;

        long total = ((long)h * 3600) + ((long)min * 60) + sec;
        return total is >= 0 and <= int.MaxValue ? (int)total : null;
    }

    /// <summary>Parse one optional h/m/s capture group; an unmatched group is 0, an out-of-range one fails.</summary>
    private static bool TryParseComponent(Group group, out int value)
    {
        if (!group.Success) { value = 0; return true; }
        return int.TryParse(group.Value, out value);
    }

    public static bool IsVideoId(string? id) => id is not null && VideoIdRegex.IsMatch(id);

    /// <summary>
    /// Whether <paramref name="url"/> is a YouTube <c>/watch</c> video page (or a <c>youtu.be</c> share
    /// link) — the only surface Auto pops out (spec §6.1). Excludes <c>/shorts/</c>, <c>/embed/</c>,
    /// <c>/playlist</c>, search, and the home page, so Auto does not fire while scrolling Shorts (which
    /// also resolve to a video id). Pure URL-shape check; says nothing about playback.
    /// </summary>
    public static bool IsWatchUrl(string? url)
    {
        if (string.IsNullOrWhiteSpace(url)) return false;
        var text = url.Trim();
        if (!text.Contains("://")) text = "https://" + text;
        if (!Uri.TryCreate(text, UriKind.Absolute, out var uri)) return false;
        if (uri.Scheme != Uri.UriSchemeHttp && uri.Scheme != Uri.UriSchemeHttps) return false;

        var host = uri.Host.ToLowerInvariant();
        if (host == "youtu.be")
            return uri.AbsolutePath.Trim('/').Length > 0;   // youtu.be/<id> is a watch-video share link
        if (!NavigationPolicy.IsYouTubeHost(host)) return false;
        return string.Equals(uri.AbsolutePath.TrimEnd('/'), "/watch", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Mixes/radios (list ids starting with "RD") play natively on the full watch page, so Normal
    /// popouts carry them like any playlist (spec 22.1, 2026-08-09 design). Only the compact URL
    /// builders omit them — the IFrame API cannot load auto-generated lists.
    /// </summary>
    internal static bool IsAutoGeneratedList(string? list) =>
        list is not null && list.StartsWith("RD", StringComparison.OrdinalIgnoreCase);

    private static void ApplyList(YouTubeTarget target, string list)
    {
        if (string.IsNullOrEmpty(list)) return;
        // Charset-validate like VideoId: the id is re-interpolated into built URLs, so a decoded
        // query value carrying '&'/'=' must never round-trip into them (spec 17: degrade, not mangle).
        if (!PlaylistIdRegex.IsMatch(list))
        {
            // The user pasted a playlist link and is getting a single video: say so (Q-6
            // non-blocking note) instead of dropping the list silently.
            if (target.VideoId is not null)
                target.FallbackReason = "That playlist link couldn't be read - popped out the current video.";
            return;
        }
        target.PlaylistId = list;
    }

    private static Dictionary<string, string> ParseQuery(string query)
    {
        var dict = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (string.IsNullOrEmpty(query)) return dict;

        foreach (var pair in query.TrimStart('?').Split('&', StringSplitOptions.RemoveEmptyEntries))
        {
            var idx = pair.IndexOf('=');
            if (idx < 0)
            {
                dict[Uri.UnescapeDataString(pair)] = string.Empty;
            }
            else
            {
                var key = Uri.UnescapeDataString(pair[..idx]);
                var value = Uri.UnescapeDataString(pair[(idx + 1)..]);
                dict[key] = value;
            }
        }
        return dict;
    }
}
